### ISSUE TITLE
Fatal error on any update

### ISSUE THREAD

**Issue by pie6k** [sgress454/sails-hook-autoreload#51] opened 2016-01-18 21:11 UTC
Hi, I'm getting error on every update of file.

I'll try tu supply every detail I can, if you need more, just tell me what.

Error I get:

```
/usr/local/lib/node_modules/sails/node_modules/sails-disk/node_modules/waterline-criteria/lib/query.js:56
    tuple[INDEX_IN_ORIG_DATA] = i;
                              ^

TypeError: Cannot set property '.(ørigindex)' of null
    at /usr/local/lib/node_modules/sails/node_modules/sails-disk/node_modules/waterline-criteria/lib/query.js:56:31
    at Function.forEach (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:3298:15)
    at query (/usr/local/lib/node_modules/sails/node_modules/sails-disk/node_modules/waterline-criteria/lib/query.js:55:5)
    at Database.select (/usr/local/lib/node_modules/sails/node_modules/sails-disk/lib/database.js:316:19)
    at Object.module.exports.adapter.find (/usr/local/lib/node_modules/sails/node_modules/sails-disk/lib/adapter.js:86:28)
    at module.exports.find (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:120:13)
    at afterDescribe (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/alter.js:103:10)
    at wrapper (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at /usr/local/lib/node_modules/sails/node_modules/sails-disk/lib/database.js:262:5
    at Database.getCollection (/usr/local/lib/node_modules/sails/node_modules/sails-disk/lib/database.js:141:3)
    at Database.describe (/usr/local/lib/node_modules/sails/node_modules/sails-disk/lib/database.js:258:8)
    at Object.module.exports.adapter.describe (/usr/local/lib/node_modules/sails/node_modules/sails-disk/lib/adapter.js:72:28)
```

I've checked those 'tuples' at top on error stack and it's array of 3 nulls.

This is my package.js deps

```
  "dependencies": {
    "bson": "^0.4.20",
    "connect-mongo": "^0.4.2",
    "ejs": "~0.8.4",
    "grunt": "0.4.2",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-coffee": "~0.10.1",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-jst": "~0.6.0",
    "grunt-contrib-less": "0.11.1",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-sails-linker": "~0.9.5",
    "grunt-sync": "~0.0.4",
    "include-all": "~0.1.3",
    "lodash": "^4.0.0",
    "node-promise": "^0.5.12",
    "rc": "~0.5.0",
    "sails": "~0.11.3",
    "sails-disk": "~0.10.0",
    "sails-hook-autoreload": "^0.12.0",
    "sails-hook-parametized-policies": "^0.3.1",
    "shortid": "^2.2.4"
  }
```

My sails version is `0.11.3`.

**Comment by sgress454** [comment] 2016-01-21 17:04
Hi @adampietrasiak, thanks for using sails-hook-autoreload.  I can't recreate this issue locally ("fatal error on any update" would be kind of a showstopper!).  If you could provide a link to a repo that would help reproduce the problem, that would be ideal.  I'd also like to know your Node/NPM version and operating system.

**Comment by sgress454** [comment] 2016-02-04 15:15
It looks like this is a general Sails issue that may be fixed by just wiping your `node_modules` and doing an `npm install` (https://github.com/balderdashy/sails/issues/3537).

**Comment by sgress454** [comment] 2016-03-17 22:31
Closing due to inactivity.

**Closed as completed by sgress454** 2016-03-17 22:31 UTC
